---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: datawire
  namespace: kube-system
spec:
  interval: 5m0s
  url: https://app.getambassador.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emissary-ingress
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: emissary-ingress
      version: '8.6.0'
      sourceRef:
        kind: HelmRepository
        name: datawire
        namespace: kube-system
      interval: 1m
  # values:
  #   replicaCount: 2
