apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
  namespace: default
spec:
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:latest
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          volumeMounts:
            - mountPath: /usr/share/audiobooks
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: audiobookshelf-data
---
apiVersion: v1
kind: Service
metadata:
  name: audiobookshelf
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 13378
  selector:
    app: audiobookshelf
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-data
  namespace: default
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: default # a standard SSD
